default:
  image:
    name: ${CI_REGISTRY}/ukos-git/docker-igorpro

test:
  script:
    - ln -rs app "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/utilities"
    - igorpro tests/tests.pxp  2>error.log | tee igorpro.log
    - if grep -e "^utilities-.*\.ipf.[0-9]\+.[0-9]\+.\serror." error.log; then exit 1; fi
  artifacts:
    paths:
      - error.log
